name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          echo "Building Docker image"
          sudo docker build -t my-apache2-image .

      - name: Run Docker Container
        run: |
          echo "Running Docker container"
          sudo docker run -d -p 80:80 --name apache2-container my-apache2-image
